version: '3'

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    command: yarn dev
    environment:
      REDIS_URL: redis://redis:6379
      HOST: '0.0.0.0'
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
