name: On push

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn ci

  deploy_alpha:
    needs: ci
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: zenato/docker-action@master
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        repository: ${{ secrets.REGISTRY_REPO }}
        registry: ${{ secrets.REGISTRY_URL }}
        tag: alpha
